baseURL = "https://development.xalgorithms.org/"
languageCode = "en-us"
title = "Xalgorithms Development Documentation"
theme = "hugo-theme-learn"

[params]
themeVariant = "xa"
disableNextPrev = "true"
ordersectionsby = "weight"
